name: Build Doom Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build the project
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: 'v4.4'
        target: 'esp32s3'
        path: 'mcugdx/examples/doom'

    - name: Verify the build output
      run: |
        if [ -f "mcugdx/examples/doom/build/doom.bin" ]; then
          echo "doom.bin found."
        else
          echo "doom.bin not found!"
          exit 1
        fi
